### PR TITLE
Fix typing issue for angular 12

### PR DESCRIPTION
**Pull request by nzacca**
Hello!

This is my first time submitting to this repository so please excuse any missed coding requirements. I couldn't find a `CONTRIBUTING` doc to adhere to (the one linked on the README appears to be broken).

This PR fixes a typing issue with Angular 12 as described by #501 .

Please let me know if any changes are required and I'll be happy to make them to get this merged. Thank you!

### CODE REVIEW

**Comment by uNmAnNeR** [comment]
@nzacca hi, thanks!

**Comment by nzacca** [comment]
@uNmAnNeR 

Thank you very much!

**Comment by kjteh** [comment]
Any idea when we will get a new publish of this changes?

**Comment by Odonno** [comment]
+1

**Pull request merged**
