### PR TITLE
refactor: vue imask composable

### PR DESCRIPTION
**Pull request by daniil4udo**
This pull request aims to enhance the element and options watchers by incorporating the `nextTick` function.

The motivation behind this update stems from a significant issue in my application, where over 300 fields experienced shuffling. This unsettling behavior seemed to be caused by the disarray of input refs.

By integrating the `nextTick` functionality, this problem is effectively resolved. 

Additionally, this PR involves

- the removal of intermediate primitive values 
- introduces the separation of element and options watchers
- utilizing a deep watcher for the options.
- move return interface of the `useIMask` to `ComposableReturn` type

These changes not only improve performance but also contribute to a cleaner and more maintainable codebase.

### CODE REVIEW

**Comment by uNmAnNeR** [comment]
hi. thanks for the PR. But i did not understand the problem you are trying to solve.
Can you give a simple example so i can check and run it by myself?
other notes:
1. please keep the original indentation
2. it seems like it's better to handle el/props changes in one watcher like `watch([el, props] => handle)` because it uses the same logic and should work consistently when el and props are changed together. Does it make sense?

**Comment by daniil4udo** [comment]
Thank you for your response @uNmAnNeR . Pushed.

PROBLEM: DOM updates have to be done in the `nextTick`, otherwise UI has not enough time to update if operation is too heavy (like in my case bunch of mask fields)

If you want same watch logic for both, at least lets add `deep` in case just some option has been changed, otherwise watcher won't run.

**Comment by daniil4udo** [comment]
I am sure there is much better an in-depth explanation, and I would love to share a reproduction for my issue, that I have been trying to trace for a week.

But the `nextTick` execution has fixed the issue.

**Comment by uNmAnNeR** [comment]
@daniil4udo hey! 
why did you close it?

**Pull request closed without merging**
