### PR TITLE
Update angular-imask

### PR DESCRIPTION
**Pull request by listepo-alterpost**
@uNmAnNeR  `ng-packagr` should work with `lerna`
Fixed https://github.com/uNmAnNeR/imaskjs/issues/115

### CODE REVIEW

**Comment by listepo-alterpost** [comment]
@uNmAnNeR do you have any comments?

**Comment by listepo-alterpost** [comment]
ng-packagr is official package builder for Angular Package Format.

**Comment by uNmAnNeR** [comment]
@listepo-alterpost hi, thanks for PR. My thoughts are the same. I suppose #115 can be fixed without additional wrappers. I'am not sure if `Angular Package Format` official itself? Any links from angular.io? For me it seems that ng-packager and Angular Package Format came from one non-official source.

**Comment by listepo-alterpost** [comment]
@uNmAnNeR  if you create a library for `npm` it will be with `ng-packagr` https://github.com/angular/angular-cli/blob/09149fe5e4f99ce4e034178c21ed158d3568136f/packages/angular_devkit/build_ng_packagr/package.json#L14

**Comment by uNmAnNeR** [comment]
ok, convinced. I don't mind, just need some time to check all this angular wrappers.
thanks!

**Comment by listepo-alterpost** [comment]
thanks, I'll wait (PS, they use rollup inside)

**Comment by listepo-alterpost** [comment]
@uNmAnNeR any news?

**Comment by uNmAnNeR** [comment]
@listepo-alterpost sorry, was very busy on this week. Can we get rid of using `tslib` in deps? Or it is mandatory?

**Comment by listepo-alterpost** [comment]
@uNmAnNeR  yes we can, it is needed for optimization

**Comment by uNmAnNeR** [comment]
@listepo-alterpost hi! btw thanks for PR :) but...
https://travis-ci.com/uNmAnNeR/imaskjs/jobs/218936340#L643
build failed, locally it works. May be you have any suggestions?

**Comment by listepo-alterpost** [comment]
@uNmAnNeR `angular-imask/node_modules` should contain imask before the build, `npm i` should fix this.

**Comment by listepo-alterpost** [comment]
How to do it in `Lerna` I do not know

**Comment by listepo-alterpost** [comment]
I think if you move the `imask` in the `peerDependencies` it should help

**Comment by uNmAnNeR** [comment]
@listepo-alterpost yes, it probably should, but it will break current approach to just install `angular-imask` without `imask` peer.
`npm i` inside package seems bad practice in `lerna`, and i use hoisting...
So lets investigate on this a little bit. I am sure there should be a proper way to solve this, i've created PR to continue working on it: https://github.com/uNmAnNeR/imaskjs/pull/223

**Pull request merged**
