### PR TITLE
feat: solid-imask implementation proposal

### PR DESCRIPTION
**Pull request by i-Welch**
**Work Done**
-
- Proposal for the solid-imask package

**To Test**
-
- npm run build in the packages/solid-imask folder
- copy /dist+package.json to node-modules of a solid project
- make sure the project has i-mask pre-installed
- test the api and type inference

### CODE REVIEW

**Comment by atk** [comment]
This reduces the imask fields to textarea, but you could also use contenteditable divs or textareas. In order to do so, you could create an imask directive.

**Comment by atk** [comment]
As the creator of @solid-primitives/input-mask, I say: that's a really nice adaption and I am happy that our users get more choice. 👍

**Comment by i-Welch** [comment]
Thanks for the help with it! I'll be doing some more extensive testing with it but I think this is a good first pass and the idea to add a masked directive was great.

**Comment by atk** [comment]
I wanted for input-mask to originally be a directive, but an event handler factory was smaller and simpler (and could also be re-used for other frameworks).

**Comment by i-Welch** [comment]
Verified and tested both methods (directive and make input) in a test project. All working as expected. Type definitions work properly as well

**Comment by uNmAnNeR** [comment]
thank you all guys. I think to keep it consistent we need also UMD build as well. I will fix it by my own. Going to add it in release 7.0 alpha.

**Pull request merged**
