### PR TITLE
Fix a bug when trying to set the mask value when overwrite option is true

### PR DESCRIPTION
**Pull request by AriasBros**
PR to fix the issue #171

### CODE REVIEW

**Comment by uNmAnNeR** [comment]
Hi! Many thanks for PR!
It's better to check here by null inequality https://github.com/uNmAnNeR/imaskjs/blob/fd08bc1226feaa39ac3f1ed446fa4b3d441338ed/packages/imask/src/masked/base.js#L252

tail != null && ...

Because in appendChar there should be no string type at all so passing empty string is a mistake.

I am from mobile phone now, will be able to fix it some days later, or it's nice if you can do it.

**Comment by AriasBros** [comment]
Hi Alexey! Sure, I can modify the PR, no problem. I will try to push the modifications today.

**Comment by AriasBros** [comment]
BTW, Alexey, I don't know if the test I added is placed in the right place. Let me know if you have other preference about this.

**Comment by uNmAnNeR** [comment]
Tests are fine, thanks

**Comment by AriasBros** [comment]
> Hi! Many thanks for PR!
> It's better to check here by null inequality
> 
> https://github.com/uNmAnNeR/imaskjs/blob/fd08bc1226feaa39ac3f1ed446fa4b3d441338ed/packages/imask/src/masked/base.js#L252
> 
> tail != null && ...
> 
> Because in appendChar there should be no string type at all so passing empty string is a mistake.
> 
> I am from mobile phone now, will be able to fix it some days later, or it's nice if you can do it.

Done Alexey!

**Comment by henriquepalato** [comment]
Hello uNmAnNeR,
I still have this problem.

On the return of my api it looks like this:

"situationDate": "2005-09-24T00: 00: 00",
"lastUpdate": "2020-01-25T23: 59: 00",
"shareCapital": 20.00,
"stateRegistration": "0",
"municipalRegistration": "",

The Component is configured as follows:
readonly imaskMoney = {
    mask: Number,
    overwrite: true,
    scale: 2,
    thousandsSeparator: '.',
    padFractionalZeros: true,
    normalizeZeros: true,
    radix: ',',
    signed: false,
    min: 0
  };

In formBuilder like this:
situationDate: ['', [Validators.required]],
lastUpdate: ['', [Validators.required]],
shareCapital: [0, [Validators.required]],
stateRegistration: ['0', [Validators.required]],
municipalRegistration: [''],

In HTML:
<input type = "text" class = "form-control text-right" id = "shareCapital" formControlName = "shareCapital" [imask] = "imaskMoney">

When I do a get in the api, this error is returning:
core.js: 6185 ERROR Error: value should be string
    at MaskedNumber.append (base.js: 187)
    at MaskedNumber.resolve (base.js: 78)
    at MaskedNumber.set (base.js: 324)
    at InputMask.set (admitjs: 368)
    at IMaskDirective.set maskValue [as maskValue] (angular-imask.js: 98)
    at IMaskDirective.writeValue (angular-imask.js: 178)
    at forms.js: 3438
    at forms.js: 4822
    at Array.forEach (<anonymous>)
    at FormControl.setValue (forms.js: 4818)

This only happens when I use [imask] = "imaskMoney"

What's wrong?

**Comment by uNmAnNeR** [comment]
@henriquepalato you probably forgot to use `[unmask]` property

**Comment by henriquepalato** [comment]
@uNmAnNeR,
Thank uou very much.
That was it.

**Pull request merged**
