### PR TITLE
fix: stringify exponential numbers properly

### LINKED ISSUE #699: Vue composable cannot handle exponential numbers
**Describe the bug**
Vue composable cannot handle numbers that js turns into exponential notation. i.e. 0.0000001 becomes 1e-7 and displays as 17 in the input. 

**To Reproduce**
Using the vue composable, type `0.000001` in an `<input>`, set a breakpoint in the composable on the watcher for `typed`, then add another zero making the number `0.0000001`. The input will turn into `17` from trying to parse `'1e-7'`. It appears it is because we are setting `mask.value.typedValue` which seems inappropriate as all we want to do is read from the IMask object. 

**Expected behavior**
Expect typing 0.0000001 in a number field using the vue composable to display `0.0000001`, not `17`.

**Environment:**
 - OS: windows
 - Browser: chrome
 - Version: 103.0.5060.114
 - IMask version: 6.4.2
 - Framework/plugin version if used: 6.4.2

**Additional context**

I'll go ahead and add a PR.

### PR DESCRIPTION
**Pull request by micDropper**
Closes #699

### CODE REVIEW

**Comment by micDropper** [comment]
Actually, the issue isn't in vue-imask, the issue is in imask
https://github.com/uNmAnNeR/imaskjs/blob/a0651deddeb1a1cd630b4bbcf361be3d7cf15e84/packages/imask/src/masked/number.js#L341

Because `String(0.0000001)` prints `'1e-7'`

There are a few ways to fix this:
https://stackoverflow.com/questions/1685680/how-to-avoid-scientific-notation-for-large-numbers-in-javascript

I'll revert the change in vue and open a PR to fix this

**Comment by micDropper** [comment]
Can I get some eyes on this @uNmAnNeR ? Thanks

**Comment by micDropper** [comment]
As an aside - I ran `npm ci` and it updated `package-lock.json` which I thought shouldn't happen. I didn't push those changes but they may be necessary

**Comment by uNmAnNeR** [comment]
@micDropper 
hey! thanks for PR.
why not just do
`.toLocaleString('en-US', { useGrouping: false, maximumFractionDigits: 20 })` ?

**Comment by micDropper** [comment]
> As an aside - I ran `npm ci` and it updated `package-lock.json` which I thought shouldn't happen. I didn't push those changes but they may be necessary

Updating to the latest node version helped. What version are you using?

**Comment by micDropper** [comment]
> @micDropper hey! thanks for PR. why not just do `.toLocaleString('en-US', { useGrouping: false, maximumFractionDigits: 20 })` ?

Hey! Thanks for the reply! I think the util function covers a larger range of numbers

`> 0.000000000000000000001.toLocaleString('en-US', { useGrouping: false, maximumFractionDigits: 20 })`
`'0'`

`> eToNumber(0.000000000000000000001)`
`'0.000000000000000000001'`

How would you feel about adding a new mask called `MaskBigNumber` that uses `bignumber.js`? It would require we add `bignumber.js` as a dependency, but we could support a far wider range of numbers and we'd have a more robust library to summon to stringify these exponentials

**Comment by uNmAnNeR** [comment]
i'd prefer not to include external dependencies. What we can do:
1. simple built-in versions with `toLocaleString`
2. a way to override this behaviour by passing callback (like `format` option)

**Comment by uNmAnNeR** [comment]
fixed in b52872620100f4bd855ceb1e0fbdf87f660037da

**Pull request closed without merging**
