### PR TITLE
Use ng packagr for angular plugin

### PR DESCRIPTION
**Pull request by uNmAnNeR**

### CODE REVIEW

**Comment by uNmAnNeR** [comment]
@listepo-alterpost finally it is merged. Thanks a lot!

**Comment by listepo-alterpost** [comment]
@uNmAnNeR you are welcome, I can not wait for the new version:)

**Comment by uNmAnNeR** [comment]
@listepo-alterpost released

**Comment by listepo-alterpost** [comment]
thanks

**Pull request merged**
