### PR TITLE
avoid error if element not exist

### PR DESCRIPTION
**Pull request by ideafm**

### CODE REVIEW

**Comment by uNmAnNeR** [comment]
Hello!
This is pertinent error. Element is required. Why it should be avoided?

**Comment by ideafm** [comment]
Because the rest of javascript is blocked if error is thrown. Maybe It make sense to simply notify that the element is required, but don't throw an error that blocks javascript

**Comment by uNmAnNeR** [comment]
This is normal, because element is required for IMask. Masking has no sense without element. If your code permits element absense the most reasonable place to check it is before masking, but not inside mask.
This is IMask usage contract. I can fix the documentation if it is not obvious.

**Comment by ideafm** [comment]
Of course check for existence element make sense, you're right. But I believe that plugin should be self sufficient, correctly handle errors and don't break whole app. This is my opinion, maybe I'm wrong.

**Comment by uNmAnNeR** [comment]
I think it is better to fall down with exception than suppose that everything is fine having error.

**Comment by ideafm** [comment]
You don't need suppose that everything is fine :) Simply need is pre checking in these case and don't execute plugin. Just return 'false'

**Pull request closed without merging**
